[pytest]
# Python path
pythonpath = .

# Test paths
testpaths = tests

# Markers
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    db: marks tests that need database

# Filter warnings
filterwarnings =
    ignore::DeprecationWarning

# Add options
addopts = -v --tb=short